import { useState, useEffect } from "react";
import { haptics } from "../utils/haptics";
import { 
  Bot, 
  ShieldCheck, 
  CheckCircle2, 
  Cpu, 
  X, 
  Check, 
  Activity,
  Phone,
  BadgeAlert
} from "lucide-react";
import { OWNER_PHONE, OWNER_NAME, dispatchWhatsAppMessage } from "../utils/notificationMatrix";

export interface UrgentApprovalItem {
  id: string;
  agentId: string;
  agentName: string;
  agentRole: string;
  agentAvatarColor: string;
  urgency: "CRITICAL" | "HIGH" | "MEDIUM";
  title: string;
  description: string;
  financialImpact?: string;
  suggestedAction: string;
  timestamp: string;
  status: "PENDING" | "APPROVED" | "REJECTED";
  actionPayload?: any;
}

export interface AgentStatusInfo {
  id: string;
  name: string;
  role: string;
  department: "Admin" | "Logistics" | "Support & BPO" | "Finance" | "QC & Data";
  status: "ACTIVE" | "ANALYZING" | "EXECUTING" | "STANDBY";
  accuracy: string;
  currentTask: string;
  tasksCompletedToday: number;
  recentTelemetry: string[];
}

interface AgenticAIOperationsModalProps {
  isOpen: boolean;
  onClose: () => void;
  onStockRefillRequested?: (sku: string, qty: number) => void;
  onDispatchOrderRequested?: (orderRef: string) => void;
}

export default function AgenticAIOperationsModal({
  isOpen,
  onClose,
  onStockRefillRequested,
  onDispatchOrderRequested,
}: AgenticAIOperationsModalProps) {
  const [activeTab, setActiveTab] = useState<"fleet" | "approvals" | "telemetry" | "logs">("approvals");
  
  // Real-time HITL Urgent Approval Queue (Persisted in localStorage)
  const [approvals, setApprovals] = useState<UrgentApprovalItem[]>(() => {
    if (typeof window !== "undefined") {
      try {
        const saved = localStorage.getItem("1aa_agentic_hitl_approvals");
        if (saved) {
          const parsed = JSON.parse(saved);
          if (Array.isArray(parsed) && parsed.length > 0) return parsed;
        }
      } catch {}
    }
    // High-fidelity active urgent decisions generated by autonomous agents
    return [
      {
        id: "hitl-001",
        agentId: "agent-finance-qc",
        agentName: "AI Data & QC Team",
        agentRole: "Pre-Dispatch Inspector & Inventory Guard",
        agentAvatarColor: "from-amber-500 to-brand-orange",
        urgency: "CRITICAL",
        title: "Immediate Restock Authorization: Collapsible Travel Kettle (0.6L)",
        description: "Stock velocity reached 38 units/day. Current factory floor inventory is 8 units (Threshold < 15). Demand model forecasts complete stockout within 6.2 hours.",
        financialImpact: "Restock: 150 Units @ ₹380 Factory Cost = ₹57,000 • Projected Gross Revenue = ₹82,350 • Margin: 30.7%",
        suggestedAction: "Trigger 1-click batch refill (+150 units) to live Mysore Central Dispatch allocation.",
        timestamp: "Just now",
        status: "PENDING",
        actionPayload: { sku: "1AA-KETL-FOLD", qty: 150 }
      },
      {
        id: "hitl-002",
        agentId: "agent-logistics",
        agentName: "AI Logistics Team",
        agentRole: "3PL Carrier Fleet Radar",
        agentAvatarColor: "from-blue-500 to-cyan-500",
        urgency: "HIGH",
        title: "Priority Air Cargo Reroute: Consignment #1AA-892182",
        description: "Surface highway congestion detected near Hubli bypass on NH-48. Rerouting via BlueDart Express Priority Air guarantees <7d SLA compliance.",
        financialImpact: "Freight Differential: +₹185 (Absorbed by 1AA 20% buffer) • Zero SLA Penalty",
        suggestedAction: "Authorize priority dispatch manifest switch to BlueDart Air Cargo.",
        timestamp: "4 mins ago",
        status: "PENDING",
        actionPayload: { orderRef: "1AA-892182", carrier: "BlueDart Air" }
      },
      {
        id: "hitl-003",
        agentId: "agent-finance",
        agentName: "AI Finance Team",
        agentRole: "Real-Time P&L Comptroller",
        agentAvatarColor: "from-emerald-500 to-teal-500",
        urgency: "MEDIUM",
        title: "Wholesale Institutional Bulk Rebate Authorization: ₹43,967 Order",
        description: "Buyer 'Karnataka Retailers Consortium' crossed 90 pieces in manifest. Automated 5% tier-2 volume discount verified against 18% GST ledger.",
        financialImpact: "Order Subtotal: ₹43,967 • 5% Volume Rebate: -₹2,198 • Net Profit Margin: 21.2% (Target: 20%)",
        suggestedAction: "Approve commercial tax invoice discount code 'B2B-BULK-90' for immediate payment link generation.",
        timestamp: "12 mins ago",
        status: "PENDING",
        actionPayload: { orderRef: "1AA-982142", rebateCode: "B2B-BULK-90" }
      }
    ];
  });

  const saveApprovals = (items: UrgentApprovalItem[]) => {
    setApprovals(items);
    if (typeof window !== "undefined") {
      localStorage.setItem("1aa_agentic_hitl_approvals", JSON.stringify(items));
    }
  };

  // Agent Fleet Status Metadata
  const [agents] = useState<AgentStatusInfo[]>([
    {
      id: "agent-admin",
      name: "AI Admin Executive",
      role: "Central Orchestrator & Rule Enforcer",
      department: "Admin",
      status: "ACTIVE",
      accuracy: "99.9%",
      currentTask: "Orchestrating agent mesh and monitoring 1AA platform health.",
      tasksCompletedToday: 184,
      recentTelemetry: [
        "Enforcing 20% flat transparent margin across all 110 active SKUs",
        "Synchronized Mysore Central Hub order queues with Axis Bank webhook ledger",
        "Dispatched daily executive briefing to owner (Abdul Darvesh)"
      ]
    },
    {
      id: "agent-logistics",
      name: "AI Logistics Team",
      role: "Carrier Fleet & Consignment Radar",
      department: "Logistics",
      status: "EXECUTING",
      accuracy: "99.4%",
      currentTask: "Tracking 24 consignments via BlueDart, Delhivery, DTDC & Shadowfax.",
      tasksCompletedToday: 342,
      recentTelemetry: [
        "BlueDart consignment #BD-891043 arrived at Bangalore Central Sort Hub",
        "Mysore Central dispatch SLA verified: 100% orders cleared within 24h",
        "Automated NDR pre-screen: Pin 570007 verified with zero return risk"
      ]
    },
    {
      id: "agent-support-bpo",
      name: "AI Customer Support & BPO",
      role: "24/7 Omnichannel Concierge",
      department: "Support & BPO",
      status: "ANALYZING",
      accuracy: "99.6%",
      currentTask: "Handling live customer WhatsApp inquiries & proforma generation.",
      tasksCompletedToday: 512,
      recentTelemetry: [
        "Resolved 34 retailer questions on master carton dimensions",
        "Automated pro-forma GST receipt dispatched to buyer in Tumkur",
        "Zero escalations: Average customer satisfaction rating 4.95 / 5.0"
      ]
    },
    {
      id: "agent-finance",
      name: "AI Finance Team",
      role: "Real-Time P&L Comptroller",
      department: "Finance",
      status: "ACTIVE",
      accuracy: "100%",
      currentTask: "Real-time COGS reconciliation & 18% GST (CGST/SGST) ledger audit.",
      tasksCompletedToday: 218,
      recentTelemetry: [
        "Gross sales ledger reconciled: ₹1,12,450 turnover verified",
        "Axis Bank UPI account 7406231167@axisbank matched with UTR entries",
        "18% GST output tax liability computed: ₹17,153 (CGST: ₹8,576.50, SGST: ₹8,576.50)"
      ]
    },
    {
      id: "agent-data-qc",
      name: "AI Data & QC Team",
      role: "Pre-Dispatch Bench Inspector",
      department: "QC & Data",
      status: "EXECUTING",
      accuracy: "99.8%",
      currentTask: "Bench testing batch quality and checking inventory soft locks.",
      tasksCompletedToday: 196,
      recentTelemetry: [
        "Bench tested 60 pcs Bubble Gun 23-hole: 100% motor pressure verified",
        "Tested 40 pcs Collapsible Travel Kettle electrical insulation: Zero DOA",
        "Soft-lock concurrency check: 0 orphan inventory locks found"
      ]
    }
  ]);

  // Live Telemetry Stream
  const [telemetryLogs, setTelemetryLogs] = useState<{ id: string; time: string; agent: string; text: string; type: "info" | "success" | "urgent" }[]>([
    { id: "tl-1", time: "15:42:10", agent: "AI Logistics", text: "BlueDart Express webhook received: AWB #BD-92182041 marked OUT_FOR_DELIVERY in Bangalore.", type: "success" },
    { id: "tl-2", time: "15:40:02", agent: "AI Finance", text: "Real-time GST ledger audit completed: 100% turnover compliant with zero variance.", type: "info" },
    { id: "tl-3", time: "15:38:15", agent: "AI Data & QC", text: "Low stock alert triggered for Collapsible Travel Kettle (8 units left). Created Urgent Approval Request #hitl-001.", type: "urgent" },
    { id: "tl-4", time: "15:35:48", agent: "AI Customer Support", text: "WhatsApp merchant inquiry auto-resolved for pincode 560001 (ETA: 4 days).", type: "info" },
    { id: "tl-5", time: "15:31:20", agent: "AI Admin Executive", text: "Heartbeat verification: All 5 agent teams operating within nominal parameters.", type: "success" }
  ]);

  // Pending count for badge
  const pendingApprovalsCount = approvals.filter(a => a.status === "PENDING").length;

  // Handle Approve action
  const handleApprove = (approvalId: string) => {
    haptics.success();
    const item = approvals.find(a => a.id === approvalId);
    if (!item) return;

    const updated = approvals.map(a => {
      if (a.id === approvalId) {
        return { ...a, status: "APPROVED" as const };
      }
      return a;
    });
    saveApprovals(updated);

    // Execute the action in the store platform
    if (item.actionPayload?.sku && item.actionPayload?.qty && onStockRefillRequested) {
      onStockRefillRequested(item.actionPayload.sku, item.actionPayload.qty);
    }
    if (item.actionPayload?.orderRef && onDispatchOrderRequested) {
      onDispatchOrderRequested(item.actionPayload.orderRef);
    }

    // Add telemetry log
    setTelemetryLogs(prev => [
      {
        id: `tl-${Date.now()}`,
        time: new Date().toLocaleTimeString("en-IN"),
        agent: item.agentName,
        text: `OWNER APPROVED: "${item.title}". Autonomous execution triggered.`,
        type: "success"
      },
      ...prev
    ]);

    // Send automated WhatsApp confirmation to store owner
    dispatchWhatsAppMessage({
      recipientPhone: OWNER_PHONE,
      type: "ADMIN_USER_ALERT",
      messageText: `⚡ *1AA AI AGENT DECISION APPROVED*\n\nAction: ${item.title}\nApproved by: ${OWNER_NAME}\nAgent: ${item.agentName}\nTimestamp: ${new Date().toLocaleTimeString('en-IN')}\nStatus: Executed in real-time on 1AA platform.`
    });
  };

  // Handle Reject action
  const handleReject = (approvalId: string) => {
    haptics.light();
    const item = approvals.find(a => a.id === approvalId);
    if (!item) return;

    const updated = approvals.map(a => {
      if (a.id === approvalId) {
        return { ...a, status: "REJECTED" as const };
      }
      return a;
    });
    saveApprovals(updated);

    setTelemetryLogs(prev => [
      {
        id: `tl-${Date.now()}`,
        time: new Date().toLocaleTimeString("en-IN"),
        agent: item.agentName,
        text: `OWNER REJECTED: "${item.title}". Autonomous action aborted.`,
        type: "urgent"
      },
      ...prev
    ]);
  };

  // Keyboard escape
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape" && isOpen) onClose();
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  return (
    <div 
      className="fixed inset-0 z-[125] flex items-center justify-center p-3 sm:p-6 bg-obsidian-950/85 backdrop-blur-2xl animate-fade-in select-none"
      onClick={onClose}
    >
      <div 
        onClick={(e) => e.stopPropagation()}
        className="relative w-full max-w-5xl bg-obsidian-900 border border-brand-orange/30 rounded-3xl shadow-[0_20px_80px_rgba(249,115,22,0.15)] flex flex-col max-h-[92vh] overflow-hidden backdrop-blur-3xl"
      >
        {/* Glow ambient background accents */}
        <div className="absolute -top-32 -right-32 w-80 h-80 bg-brand-orange/15 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute -bottom-32 -left-32 w-80 h-80 bg-brand-blue/15 rounded-full blur-3xl pointer-events-none" />

        {/* Modal Header */}
        <div className="relative z-10 px-5 sm:px-8 py-4 sm:py-5 border-b border-white/[0.08] flex items-center justify-between bg-obsidian-950/70 backdrop-blur-md">
          <div className="flex items-center gap-3">
            <div className="w-11 h-11 rounded-2xl bg-gradient-to-tr from-brand-orange via-amber-500 to-cyan-400 flex items-center justify-center text-obsidian-950 shadow-glow-orange shrink-0">
              <Bot className="w-6 h-6 stroke-[2.5]" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-base sm:text-lg font-black text-white font-mono tracking-tight uppercase">
                  1AA Autonomous Multi-Agent Operations HQ
                </h2>
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 font-bold uppercase tracking-wider flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-ping" />
                  5 Agents Active
                </span>
              </div>
              <p className="text-[11px] text-slate-400 font-mono">
                Admin • Logistics • Support & BPO • Finance • Data & QC • Human-In-The-Loop Approval Feed
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2.5">
            <div className="hidden sm:flex items-center gap-1.5 px-3 py-1 rounded-full bg-white/[0.04] border border-white/10 text-[11px] font-mono text-slate-300">
              <Phone className="w-3 h-3 text-brand-orange" />
              <span>Direct Hotline: <strong className="text-white">+91 74062 31167</strong> ({OWNER_NAME})</span>
            </div>

            <button
              onClick={() => {
                haptics.light();
                onClose();
              }}
              className="w-9 h-9 rounded-full bg-white/[0.06] hover:bg-white/[0.12] text-slate-400 hover:text-white flex items-center justify-center transition-colors cursor-pointer"
              title="Close Operations Window"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Tab Navigation Strip */}
        <div className="relative z-10 px-5 sm:px-8 py-2.5 bg-obsidian-950/40 border-b border-white/[0.06] flex items-center gap-2 overflow-x-auto scrollbar-none">
          <button
            onClick={() => { haptics.selection(); setActiveTab("approvals"); }}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-bold font-mono transition-all flex items-center gap-2 cursor-pointer shrink-0 ${
              activeTab === "approvals"
                ? "bg-brand-orange text-obsidian-950 shadow-glow-orange"
                : "text-slate-400 hover:text-white hover:bg-white/[0.05]"
            }`}
          >
            <BadgeAlert className="w-3.5 h-3.5" />
            <span>Urgent Approvals</span>
            {pendingApprovalsCount > 0 && (
              <span className={`px-1.5 py-0.2 rounded-full text-[10px] font-black ${
                activeTab === "approvals" ? "bg-obsidian-950 text-brand-orange" : "bg-brand-orange text-obsidian-950"
              }`}>
                {pendingApprovalsCount}
              </span>
            )}
          </button>

          <button
            onClick={() => { haptics.selection(); setActiveTab("fleet"); }}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-bold font-mono transition-all flex items-center gap-2 cursor-pointer shrink-0 ${
              activeTab === "fleet"
                ? "bg-brand-orange text-obsidian-950 shadow-glow-orange"
                : "text-slate-400 hover:text-white hover:bg-white/[0.05]"
            }`}
          >
            <Cpu className="w-3.5 h-3.5" />
            <span>Active Agent Fleet</span>
            <span className="text-[10px] px-1.5 py-0.2 rounded-full bg-white/10 text-slate-300">5</span>
          </button>

          <button
            onClick={() => { haptics.selection(); setActiveTab("telemetry"); }}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-bold font-mono transition-all flex items-center gap-2 cursor-pointer shrink-0 ${
              activeTab === "telemetry"
                ? "bg-brand-orange text-obsidian-950 shadow-glow-orange"
                : "text-slate-400 hover:text-white hover:bg-white/[0.05]"
            }`}
          >
            <Activity className="w-3.5 h-3.5" />
            <span>Live Telemetry & Logs</span>
          </button>
        </div>

        {/* Tab Content Body */}
        <div className="relative z-10 flex-1 overflow-y-auto p-5 sm:p-8 space-y-6">
          
          {/* TAB 1: URGENT APPROVALS (HITL - HUMAN IN THE LOOP) */}
          {activeTab === "approvals" && (
            <div className="space-y-4">
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 p-4 rounded-2xl bg-white/[0.03] border border-white/[0.06]">
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-xl bg-amber-500/20 border border-amber-500/40 flex items-center justify-center text-amber-300 shrink-0">
                    <ShieldCheck className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="text-sm font-bold text-white font-mono">
                      Human-In-The-Loop (HITL) Executive Governance
                    </h3>
                    <p className="text-xs text-slate-400">
                      Autonomous AI agents detect critical bottlenecks and submit high-impact actions for your 1-click authorization.
                    </p>
                  </div>
                </div>

                <div className="text-xs font-mono text-slate-400">
                  Pending Authorizations: <strong className="text-brand-orange font-bold">{pendingApprovalsCount}</strong>
                </div>
              </div>

              {/* Approvals List */}
              <div className="space-y-3">
                {approvals.map((item) => (
                  <div 
                    key={item.id}
                    className={`p-5 rounded-2xl border transition-all ${
                      item.status === "PENDING"
                        ? "bg-obsidian-950/80 border-brand-orange/40 shadow-lg"
                        : item.status === "APPROVED"
                        ? "bg-emerald-950/20 border-emerald-500/30 opacity-75"
                        : "bg-red-950/20 border-red-500/30 opacity-60"
                    }`}
                  >
                    <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4">
                      
                      {/* Left: Agent Badge & Description */}
                      <div className="space-y-2 flex-1">
                        <div className="flex flex-wrap items-center gap-2">
                          <span className={`text-[10px] px-2.5 py-0.5 rounded-full font-mono font-bold uppercase tracking-wider ${
                            item.urgency === "CRITICAL"
                              ? "bg-red-500/20 text-red-300 border border-red-500/40 animate-pulse"
                              : item.urgency === "HIGH"
                              ? "bg-amber-500/20 text-amber-300 border border-amber-500/40"
                              : "bg-blue-500/20 text-blue-300 border border-blue-500/40"
                          }`}>
                            {item.urgency}
                          </span>

                          <span className="text-xs font-mono font-bold text-brand-orange flex items-center gap-1.5">
                            <Bot className="w-3.5 h-3.5" />
                            {item.agentName} ({item.agentRole})
                          </span>

                          <span className="text-white/20">•</span>

                          <span className="text-[11px] text-slate-500 font-mono">
                            {item.timestamp}
                          </span>
                        </div>

                        <h4 className="text-sm sm:text-base font-black text-white leading-snug">
                          {item.title}
                        </h4>

                        <p className="text-xs text-slate-300 leading-relaxed font-sans">
                          {item.description}
                        </p>

                        {item.financialImpact && (
                          <div className="text-[11px] text-emerald-400 font-mono bg-emerald-950/40 border border-emerald-500/30 p-2.5 rounded-xl">
                            <strong>Impact Analysis:</strong> {item.financialImpact}
                          </div>
                        )}

                        <div className="text-xs text-slate-400 font-mono">
                          <strong>Recommended Action:</strong> {item.suggestedAction}
                        </div>
                      </div>

                      {/* Right: Actions */}
                      <div className="flex items-center gap-2 shrink-0 w-full lg:w-auto pt-2 lg:pt-0">
                        {item.status === "PENDING" ? (
                          <>
                            <button
                              onClick={() => handleReject(item.id)}
                              className="flex-1 lg:flex-none px-4 py-2.5 rounded-xl bg-white/[0.06] hover:bg-white/[0.12] border border-white/10 text-slate-300 hover:text-white font-mono font-bold text-xs transition-colors cursor-pointer"
                            >
                              Reject
                            </button>
                            <button
                              onClick={() => handleApprove(item.id)}
                              className="flex-1 lg:flex-none px-5 py-2.5 rounded-xl bg-gradient-to-r from-brand-orange to-amber-500 hover:brightness-110 text-obsidian-950 font-mono font-black text-xs uppercase tracking-wider shadow-glow-orange flex items-center justify-center gap-2 transition-all cursor-pointer active:scale-95"
                            >
                              <Check className="w-4 h-4 stroke-[3]" />
                              <span>Approve & Execute</span>
                            </button>
                          </>
                        ) : item.status === "APPROVED" ? (
                          <div className="flex items-center gap-2 text-emerald-400 font-mono text-xs font-bold bg-emerald-500/10 border border-emerald-500/30 px-3 py-1.5 rounded-xl">
                            <CheckCircle2 className="w-4 h-4" />
                            <span>APPROVED & EXECUTED</span>
                          </div>
                        ) : (
                          <div className="flex items-center gap-2 text-red-400 font-mono text-xs font-bold bg-red-500/10 border border-red-500/30 px-3 py-1.5 rounded-xl">
                            <X className="w-4 h-4" />
                            <span>REJECTED BY OWNER</span>
                          </div>
                        )}
                      </div>

                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* TAB 2: AGENT FLEET STATUS */}
          {activeTab === "fleet" && (
            <div className="space-y-4">
              <div className="text-xs text-slate-400 font-mono">
                Continuous autonomous monitoring across all 5 operational vectors. Agents adhere strictly to 1AA pricing covenants and zero-middlemen principles.
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {agents.map((agent) => (
                  <div 
                    key={agent.id}
                    className="p-5 rounded-2xl bg-white/[0.03] border border-white/[0.08] hover:border-brand-orange/40 transition-all space-y-3 text-left"
                  >
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2.5">
                        <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-brand-orange to-brand-blue flex items-center justify-center text-obsidian-950 font-bold shadow-sm">
                          <Bot className="w-5 h-5" />
                        </div>
                        <div>
                          <h4 className="text-sm font-bold text-white font-mono">{agent.name}</h4>
                          <span className="text-[10px] text-slate-400 font-mono">{agent.role}</span>
                        </div>
                      </div>

                      <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 font-mono font-bold flex items-center gap-1">
                        <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                        {agent.status}
                      </span>
                    </div>

                    <div className="p-3 rounded-xl bg-black/40 border border-white/[0.04] space-y-1">
                      <div className="text-[10px] uppercase font-mono text-slate-500">Current Autonomous Task:</div>
                      <div className="text-xs text-slate-200 font-mono leading-relaxed">{agent.currentTask}</div>
                    </div>

                    <div className="space-y-1.5">
                      <div className="text-[10px] uppercase font-mono text-slate-500">Live Agent Telemetry:</div>
                      <div className="space-y-1">
                        {agent.recentTelemetry.map((t, idx) => (
                          <div key={idx} className="text-[11px] text-slate-300 font-mono flex items-start gap-1.5">
                            <span className="text-brand-orange mt-0.5">•</span>
                            <span>{t}</span>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="pt-2 border-t border-white/[0.06] flex items-center justify-between text-[11px] font-mono text-slate-400">
                      <span>Tasks Executed Today: <strong className="text-white">{agent.tasksCompletedToday}</strong></span>
                      <span>Precision: <strong className="text-emerald-400">{agent.accuracy}</strong></span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* TAB 3: LIVE TELEMETRY & AUDIT STREAM */}
          {activeTab === "telemetry" && (
            <div className="space-y-3 text-left">
              <div className="flex items-center justify-between text-xs font-mono text-slate-400 pb-2">
                <span>Real-Time Autonomous Mesh Execution Feed</span>
                <span className="flex items-center gap-1.5 text-emerald-400">
                  <span className="w-2 h-2 rounded-full bg-emerald-400 animate-ping" />
                  Streaming Live
                </span>
              </div>

              <div className="space-y-2 font-mono text-xs">
                {telemetryLogs.map((log) => (
                  <div 
                    key={log.id}
                    className="p-3 rounded-xl bg-white/[0.03] border border-white/[0.06] flex items-start gap-3"
                  >
                    <span className="text-slate-500 text-[11px] shrink-0 pt-0.5">{log.time}</span>
                    <span className={`text-[10px] px-2 py-0.5 rounded-full font-bold uppercase shrink-0 ${
                      log.type === "urgent" 
                        ? "bg-red-500/20 text-red-300 border border-red-500/30"
                        : log.type === "success"
                        ? "bg-emerald-500/20 text-emerald-400 border border-emerald-500/30"
                        : "bg-blue-500/20 text-blue-300 border border-blue-500/30"
                    }`}>
                      {log.agent}
                    </span>
                    <span className="text-slate-200 flex-1 leading-relaxed">{log.text}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

        </div>

        {/* Modal Footer */}
        <div className="relative z-10 px-5 sm:px-8 py-3.5 bg-obsidian-950 border-t border-white/[0.08] flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-slate-400 font-mono">
          <div>
            1AA Autonomous Mesh • Mysore Central Facility • Licensed to {OWNER_NAME} (+91 {OWNER_PHONE})
          </div>

          <div className="flex items-center gap-2">
            <span className="text-emerald-400 font-bold">● 100% Agentic Governance Active</span>
          </div>
        </div>

      </div>
    </div>
  );
}
